# Generated by Django 4.2.1 on 2023-05-27 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('email_responsavel', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('telefone_responsavel', models.CharField(max_length=15)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.nivel')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.serie')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.turno')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.unidade')),
            ],
        ),
    ]
