# Generated by Django 4.2.1 on 2023-05-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataAdmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissão', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegimeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Titulação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulação', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('admissão', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.dataadmissao')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.cargo')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.escolaridade')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.regimetrabalho')),
                ('titulação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.titulação')),
            ],
        ),
    ]
