# Generated by Django 4.2.1 on 2023-05-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='admissão',
            new_name='admissao',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='titulação',
            new_name='titulacao',
        ),
    ]
